### ISSUE TITLE
Spanner EFW Scaffolding is not working and throwing below exception

### ISSUE THREAD

**Issue by sadut4** [googleapis/dotnet-spanner-entity-framework#274]
Hi, 
I am using Entity framework for spanner and trying to scaffold our existing database and generate the codebase but getting the below exception again and again. I am running below command:

PM> Scaffold-DbContext "Data Source=projects/GCP_Project/instances/SPANNER_Instance/databases/DB_Name" Google.Cloud.EntityFrameworkCore.Spanner

![image](https://user-images.githubusercontent.com/91130523/212265995-b7a2c008-ae97-410b-a9c7-bf02b86ef500.png)

Here is my .csproj file dependencies:

![image](https://user-images.githubusercontent.com/91130523/212266243-34220aa8-1ad1-45b2-b29d-26fce760e790.png)

Please let me know if any scaffold works with any specific version or what is the issue.

#### Environment details

  - Programming language:
  - OS: Windows 10
  - Language runtime version: net6.0
  - Package version:

#### Steps to reproduce

  1. ?
  2. ?

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by olavloite** [comment]
@sadut4 My guess is that the problem is caused by the different versions of the different parts of Entity Framework that you are adding to your project:
1. The Cloud Spanner Entity Framework provider v 2.x is intended for Entity Framework 6.x.
2. You are adding EntityFrameworkCore 7.0.2 to your project.
3. You are also adding a number of EntityFrameworkCore 6.0.11 dependencies to your project (Design, Proxies, Relational). That is the correct version when working with EntityFrameworkCore.Spanner version 2.0.6.
4. And there is a EntityFrameworkTools v3.1.0 in your project.

Try to remove as many of those dependencies as possible and rely on the transitive dependencies that are automatically added by the `Google.Cloud.EntityFrameworkCore.Spanner` dependency. That package will automatically add the correct version of Entity Framework to your project. If you are still missing any specific dependencies, then make sure that you align the version of that dependency with the other version(s) of EntityFrameworkCore that you are pulling in (that is; version 6.0.11)

**Comment by slideep** [comment]
Just wanted to pitch in and say that Entity Framework Core .NET CLI Tools, e.g. `dotnet ef database update`, `dotnet ef migrations add` etc. work OOB great if one doesn't use Visual Studio (and PMC tools of course work as well). For the original poster, here's what I use as my only deps: 

![image](https://user-images.githubusercontent.com/100609/227849017-86cf6746-8a16-420b-9bb6-e54026dec009.png)

Good luck!
