### ISSUE TITLE
When will you target .net 8?

### ISSUE THREAD

**Issue by jhammetts** [googleapis/dotnet-spanner-entity-framework#386]
We use the Google.Cloud.EntityFrameworkCore.Spanner library in our .net 6 application. We are upgrading to use .net 8 given that .net 6 will no longer be supported by MS after Nov 2024.  However, we're encountering a runtime error from our DbContext constructor with the spanner provider that is not present when we run with .net 6:

`Method 'FindMapping' in type 'Google.Cloud.EntityFrameworkCore.Spanner.Storage.Internal.SpannerTypeMappingSource' from assembly 'Google.Cloud.EntityFrameworkCore.Spanner, Version=2.1.3.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.`

We are also wary about having a dependency on a library that targets a version of .net that will be out of support soon.

Do you expect to update the EF provider for spanner to target .net 8 soon?

**Comment by ANIZA15** [comment]
I am currently experiencing the same phenomenon myself. I would like to see a successful net8.0 dependency package rolled out as soon as possible.

**Comment by olavloite** [comment]
Note that there are two relevant things related to this:
1. Target .NET 8. That is relatively straightforward.
2. Target Entity Framework 8, as Entity Framework 6 also goes out of support in Nov 2024 (see https://learn.microsoft.com/en-us/ef/core/what-is-new/)

**Comment by olavloite** [comment]
A quick update on this:
1. We will be rolling out support for .NET 8 in #403. That will make the library useable for applications targeting both .NET 6 and .NET 8. It will at that moment continue to use Entity Framework 6. This change is currently awaiting some infrastructure changes that are needed in order to support releasing the library for both .NET 6 and .NET 8.
2. We will do an upgrade of the library to support Entity Framework Core 8 in a separate pull request. That is likely to be a large and breaking change, as there are some large (internal) differences between Entity Framework Core 6 and Entity Framework Core 8.

**Comment by olavloite** [comment]
Version 3.0 of Entity Framework has been released and pushed to NuGet. This version requires .NET 8 and Entity Framework 8.
